// <auto-generated />
using System;
using BookingSite.Web.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingSite.Web.Migrations
{
    [DbContext(typeof(BookingSiteDbContext))]
    partial class BookingSiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingSite.Web.DomainModels.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("HotelCode");

                    b.Property<string>("HotelName");

                    b.Property<int>("StarRating");

                    b.HasKey("ID");

                    b.ToTable("HotelMaster");

                    b.HasData(
                        new { ID = 1, Address = "abc", City = "Navi Mumbai", HotelCode = "NMHI", HotelName = "Hotel Inn", StarRating = 3 },
                        new { ID = 2, Address = "xyz", City = "Navi Mumbai", HotelCode = "NMHD", HotelName = "Hotel Darbar", StarRating = 3 },
                        new { ID = 3, Address = "def", City = "Mumbai", HotelCode = "MHO", HotelName = "Hotel Oberoi", StarRating = 5 }
                    );
                });

            modelBuilder.Entity("BookingSite.Web.DomainModels.HotelBooking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckoutDate");

                    b.Property<DateTime>("ChickInDate");

                    b.Property<string>("ContactPhone");

                    b.Property<DateTime>("Date");

                    b.Property<string>("HotelCode");

                    b.Property<string>("HotelName");

                    b.Property<int>("NumberOfRooms");

                    b.Property<string>("PaxName");

                    b.Property<string>("RoomType");

                    b.Property<decimal>("Tariff");

                    b.HasKey("ID");

                    b.ToTable("HotelBookings");
                });

            modelBuilder.Entity("BookingSite.Web.DomainModels.HotelRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HotelCode");

                    b.Property<string>("RoomType");

                    b.Property<decimal>("Tariff");

                    b.HasKey("ID");

                    b.ToTable("HotelRooms");

                    b.HasData(
                        new { ID = 1, HotelCode = "NMHI", RoomType = "Single", Tariff = 1500m },
                        new { ID = 2, HotelCode = "NMHI", RoomType = "Double", Tariff = 2500m },
                        new { ID = 3, HotelCode = "NMHI", RoomType = "Twin", Tariff = 2650m },
                        new { ID = 4, HotelCode = "NMHD", RoomType = "Single", Tariff = 1500m },
                        new { ID = 5, HotelCode = "NMHD", RoomType = "Double", Tariff = 2500m },
                        new { ID = 6, HotelCode = "NMHD", RoomType = "Twin", Tariff = 2650m }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
